### ISSUE TITLE
Feature Request: Watch portal marker type

### ISSUE THREAD

**Issue by cloudkucooland** [wasabee-project/Wasabee-IITC#102]
Any portals marked with this marker would be added to a list dialog showing
last activity
name
level
mods
charge level
link level (?)

Future plans for storing/sharing historical data if possible.

Need a set of marker icons (cw?)

requested by AxForest

**Comment by crystalwizard** [comment]
after discussing this with the requestor, it has become clear this is not something we can do in Wasabee. Closing this.

**Comment by cloudkucooland** [comment]
Why not, seemed legit to me?
