### ISSUE TITLE
Support Touch events, not just faked "click"

### ISSUE THREAD

**Issue by cloudkucooland** [wasabee-project/Wasabee-IITC#104]
For this to be truly mobile friendly, we have to rework some of the UI to use touch events.

**Comment by cloudkucooland** [comment]
https://www.prowebdesign.ro/how-to-deal-with-hover-on-touch-screen-devices/
http://www.javascriptkit.com/javatutors/touchevents.shtml
https://leafletjs.com/reference-1.6.0.html#domevent

**Comment by crystalwizard** [comment]
For quick draw:  The follow text seems to want to start where I touched last, even if it's not in the focus area. And the "end" flyout box vanishes soon as i touch the first portal - making it impossible to actually end the drawing when i've finished selecting all the spine portals

**Comment by cloudkucooland** [comment]
> For quick draw: The follow text seems to want to start where I touched last, even if it's not in the focus area. And the "end" flyout box vanishes soon as i touch the first portal - making it impossible to actually end the drawing when i've finished selecting all the spine portals

workaround until we can get touch working properly is to reload, it'll clear the qd handler and the links won't be lost

**Comment by cloudkucooland** [comment]
I think what we have now is work-able. Not perfect. But it will take someone who loves touch devices to make it better.
