### ISSUE TITLE
Prevent duplicate markers from being assigned to the same portal

### ISSUE THREAD

**Issue by crystalwizard** [wasabee-project/Wasabee-IITC#105]
There is a need to be able to put multiple markers of different types on a portal, but wasabee should not allow 2 markers of the same type to be assigned to the same portal. Right now there is no limit to the number of duplicate markers that can be assigned (5 destroy, 7 capture, etc)

**Comment by eagsc7** [comment]
Thinking out loud...

- Either Destroy OR Use Virus OR Let Decay
- Capture should be "Full Deploy" (Primary use is Inbound links....)
- All others, limit 2 Unassigned to each portal 

Does that sound ok?

**Comment by le-jeu** [comment]
* let the operator choose how to use the different markers
 * "Capture" could also mean capture only, the comment is useful to resolve the ambiguity if any
 * same as first point

I close the issue since the main point is fix, you may open another issue for the other points
