### ISSUE TITLE
sortables should remember the sort order while open

### ISSUE THREAD

**Issue by cloudkucooland** [wasabee-project/Wasabee-IITC#109]
it is annoying to have the ops checklist open, add a marker and lose the sort

these values could be saved in localStorage[] and preserved across open/close as well.

**Comment by bgillock** [comment]
Looking at this one. Proposing to add a callback to the Sortable constructor that is called when the SortBy or SortAsc is changed. This callback will store the new sort field and direction in local storage. This can be used in the other dialogs that use the sortable table.

**Comment by cloudkucooland** [comment]
I was just going to stuff a value in localStorage whenever the sort was changed; a set of dialog names, with a simple key-value object for the state

sortorder["blockerlist"] = { key: "comment"; asc: true };
localStorage["wasabee-sort"] = sortorder;

but if a callback makes life better down the line, go that route

**Comment by bgillock** [comment]
Is there another way to know when the sort column/direction changed?  Rather use existing functionality where possible.

**Comment by le-jeu** [comment]
depending on how long we store the information : 
 1. Local variable in each dialog `.js` with last `sortBy/sortAsc`
 2. Local mapping in sortable, and a id given at sortable construction such as `checklist => { sortBy, sortAsc }`
 3. Any of 1 or 2 but store the value in localStorage to preserve between reload
 4. (3) but with a single localStorage value with all dialog sorting parameters

**Comment by le-jeu** [comment]
by the way, the premise is now false, you lose the sorting order if you close the dialog
