### ISSUE TITLE
Provide an indication when links in the op cross other links in the op

### ISSUE THREAD

**Issue by TheSned** [wasabee-project/Wasabee-IITC#11]
It would be a nice feature to see if you have unintentionally created crossing links.

**Comment by cloudkucooland** [comment]
Yes.

Could the existing cross-link detection code be repurposed for this or would it need custom? Do we run into a recursive problem with that algo? 

One solution would be to "draw" the field in one buffer, then in a different buffer run the crossing links against that, ignoring the "same" link.

**Comment by cloudkucooland** [comment]
done in 0.16.0
