### ISSUE TITLE
Additional Exclude From  Uses... 

### ISSUE THREAD

**Issue by eagsc7** [wasabee-project/Wasabee-IITC#110]
"Make auto-mark observe exclude marker type"

The exclude from auto-draws isn't observed in the auto-mark yet, that would be a good thing to add.

**Comment by cloudkucooland** [comment]
please test

**Comment by eagsc7** [comment]
Tested and worked both times I tried it.

**Comment by cloudkucooland** [comment]
also works sanely if both ends of a blocker are marked as excluded. calling it done.
