### ISSUE TITLE
Multimax Menu doesn’t open on iPhone

### ISSUE THREAD

**Issue by cmmdr3** [wasabee-project/Wasabee-IITC#111]
The multimax menu doesn’t open on iPhone. 
Tested on iPhone 11pro iOS 13.4.1
Wasabee build 0.16.1-2020-04-18T17:38:43.104Z

**Comment by cloudkucooland** [comment]
![D7B98594-BB2C-4D20-A4AE-B2EB55FA0920](https://user-images.githubusercontent.com/8037678/79670069-e6246600-8185-11ea-9f88-9cab300e0183.png)

Loaded for me

**Comment by cloudkucooland** [comment]
Can anyone else verify with a recent build?

**Comment by crystalwizard** [comment]
This is fixed - it was an issue with let over bits of IITC from an uninstall/upgrade of IITC
