### ISSUE TITLE
Send Location Time - Fix

### ISSUE THREAD

**Issue by eagsc7** [wasabee-project/Wasabee-IITC#114]
Time is not showing up as accurate Unless in the Same Time Zone.  Even then it will "break " to UTC + Time zones.  

Times are showing as Negative (Ahead of current time) if viewer is West of the transmitting agent, and off by hours when seen as UTC + Time zone agent.

**Comment by cloudkucooland** [comment]
Is this anyone but @crystalwizard ? Check your OS clock and timezone. Use NTP, set your timezone correctly.

**Comment by eagsc7** [comment]
This was a few of us... Germany and US.  Live times were not showing as correct.  (As in Hours ago.. or hours Ahead of the actual time..
