### ISSUE TITLE
Wasabee Tooltop

### ISSUE THREAD

**Issue by eagsc7** [wasabee-project/Wasabee-IITC#120]
In About Wasabee, have a "link" open a new Tab with a list of the "Active Tooltips" where a user can "deselect" the ones they already know.  

Other options would be Select/Deselect All

Primary use would be an easy place to see Here's all the tooltips...

**Comment by cloudkucooland** [comment]
That sounds like a great tasks for someone who wants to learn how to dev for wasabee/IITC

**Comment by TheMitch2** [comment]
I put this on my list of things to accomplish.

**Comment by cloudkucooland** [comment]
That is (at minimum) one bit of state for EACH tool tip. I'd rather a single setting for either "show" or "don't show" tooltips. This is how must apps work.

**Comment by TheMitch2** [comment]
That sounds easier anyway.

**Comment by TheMitch2** [comment]
Recent changes placed the tips on the wiki and a link to the tips page on the download dialog. This issue is now moot.

**Comment by eagsc7** [comment]
sounds good!!!  thx
