### ISSUE TITLE
Metadata Block

### ISSUE THREAD

**Issue by johnd0e** [wasabee-project/Wasabee-IITC#14]
I have some suggestions about metadata improvements
<details>

```js
// ==UserScript==
// @id           wasabee
// @name         IITC Plugin: Wasabee Draw Tools
// @namespace    http://tampermonkey.net/
// @version      0.13.1-deviousness
// @updateURL    http://server.wasabee.rocks/static/dev/wasabee.meta.js
// @downloadURL  http://server.wasabee.rocks/static/dev/wasabee.user.js
// @description  Wasabee is not for dating. Period.
// @category     Draw
// @author       Wasabee
// @include      https://*.ingress.com/*
// @include      http://*.ingress.com/*
// @match        https://*.ingress.com/*
// @match        http://*.ingress.com/*
// @include      https://*.ingress.com/mission/*
// @include      http://*.ingress.com/mission/*
// @match        https://*.ingress.com/mission/*
// @match        http://*.ingress.com/mission/*
// @grant        none
// ==/UserScript==
```
</details>

Docs are here: https://wiki.greasespot.net/Metadata_Block
What is important:
- `@id` is not standard property.
   And it's not about 'uniqueness'. In fact it should correspond to filename.
- `@name` now begins with `IITC Plugin: `, it's rather convention, but most of scripts have 'plugin' in low case (`IITC plugin: Wasabee Draw Tools`) 
- `@namespace` is important for updating, together with `@name` they define uniqueness of plugin.
   It can be any string, but better pick some domain under your control.
   Definitely not http://tampermonkey.net/
- `@updateURL`, `@downloadURL` -  must have `https`, otherwise updating will not work.
- `@include` and `@match` are synonyms.
   Currently single definition is enough 
for all cases: `// @include        https://intel.ingress.com/*`
   Or `@match`, that would be equal in our case.

**Comment by cloudkucooland** [comment]
fixed  in https://github.com/wasabee-project/Wasabee-IITC/commit/7cf77578e4f817837b7f101b4e2fa1c7354fbf8c

on master. branches will catch up eventually.

**Comment by johnd0e** [comment]
I was not clear, sorry: @id expected to be name without extension. So it was OK, I just explained it's meaning.

And also I'd like to see @category field which used in mobile IITC versions.
