### ISSUE TITLE
Update fake portal marker when a matching portal is loaded

### ISSUE THREAD

**Issue by le-jeu** [wasabee-project/Wasabee-IITC#143]
at the moment, fake portals are only loaded in those cases:
 - portal data are already loaded at creation
 - portal is added into the view or user select the portal AND some dialog is open (checklist/blockerlist/...)

And it does not load if on dialog is open when portal details are loaded.

It could be an addition to load fake portal without the need of a dialog

**Comment by cloudkucooland** [comment]
> at the moment, fake portals are only loaded in those cases:
> 
> * portal data are already loaded at creation
> * portal is added into the view or user select the portal AND some dialog is open (checklist/blockerlist/...)
> 
> And it does not load if on dialog is open when portal details are loaded.
> 
> It could be an addition to load fake portal without the need of a dialog

Leaving the portalDetailsLoaded hook running all the time greatly reduced performance, and battery life on mobile devices. It is only live when specific dialogs are open for that reason.

**Comment by le-jeu** [comment]
using the updateDetails hook looks good enough for me, and since it was added in 20b13abfbdf600887e27f58a0dd6f41375d50c4c I close this issue
