### ISSUE TITLE
Problem deleting portals in the middle of using quick draw function

### ISSUE THREAD

**Issue by crystalwizard** [wasabee-project/Wasabee-IITC#159]
If, after activating quick draw layers but before ending the function, a portal is selected for the spine, and then deleted via clicking on the marker and selecting delete, wasabee will not allow the same portal to be clicked and added as a spine portal again until the current run of the quick draw layers function has ended. The portal is selectable in IITC, but wasabee does not draw links from the anchors to the portal.

 Tested on both desktop browser and in android mobile with the same results.

**Comment by le-jeu** [comment]
Related lines
https://github.com/wasabee-project/Wasabee-IITC/blob/bbdd4f47a456ffe7fb6b11c2590874ca03006d35/src/code/buttons/quickdrawButton.js#L183-L184

**Comment by le-jeu** [comment]
solved, QD doesn't care of previous portals now
