### ISSUE TITLE
Why does checkAllLinks() add itself on layer add?

### ISSUE THREAD

**Issue by TheSned** [wasabee-project/Wasabee-IITC#17]
Seems like we should only call `window.map.on("layeradd"...)` once, not every time the function is called.

**Comment by cloudkucooland** [comment]
initCrossLinks() is only called during the initialization phase, so just once.

**Comment by TheSned** [comment]
Whoops, nevermind. I think I was looking at a diff and it had collapsed some code and I thought that `on("layeradd"...)` code was called from checkAllLinks(). Closing this.
