### ISSUE TITLE
Bug - OPS showing after team toggled off

### ISSUE THREAD

**Issue by TheMitch2** [wasabee-project/Wasabee-IITC#179]
I am using the dev version of the IITC plugin.  After disabling a team that belongs to a different user, I clear local ops and download again. All ops for any team on which I am a member now show regardless of team status. This can be duplicated on Android IITC, both the chrome and Firefox browsers for Windows 10, and chrome on Windows 7.

**Comment by cloudkucooland** [comment]
Yes. This is the new intended behavior.
