### ISSUE TITLE
Checklist commands in "Assigned Only" permission scenario

### ISSUE THREAD

**Issue by SebastienForay** [wasabee-project/Wasabee-IITC#225]
When logged agent is in a team with "Assigned Only" permissions, checklist allows to delete some entries while it's not possible to upload those changes.
Deletion commands might be removed in this case.

Only state should be available for edit

**Comment by SebastienForay** [comment]
Also, order can be edited in this scenario, but shouldn't.
Entries must be disabled

**Comment by cloudkucooland** [comment]
This should be addressed along with #107  - Lets make these two a priority for 0.20
