### ISSUE TITLE
Quickdraw & Zones : Add the ability to change zone

### ISSUE THREAD

**Issue by SebastienForay** [wasabee-project/Wasabee-IITC#241]
It's impossible to choose in which zone we're drawing. User must change later in the checklist what should be in which zone with the combo-boxes.

In the quickdraw menu, add a button to change zone (bonus : the button text shows current zone)

Edit : since the recent addition of visual zones, this feature would be needed if the Op creator didn't yet drawn zones and so he can't use the "Set links to zones" and "Set markers to zones" buttons in checklist. Zones might often be drawn after the Operation draw

**Comment by cloudkucooland** [comment]
excellent idea

**Comment by le-jeu** [comment]
is a UI looping over the zones enough or do we need a dialog for this ?

**Comment by SebastienForay** [comment]
could be enough. @le-jeu can you add this so that we can test and validate if UX is good or not ?

**Comment by SebastienForay** [comment]
I've edited my first comment on this Issue to add more details

**Comment by SebastienForay** [comment]
Closing this as geographical zones addition is already good enough to fit the need
