### ISSUE TITLE
Links window : Add the ability to edit Zone for each link

### ISSUE THREAD

**Issue by SebastienForay** [wasabee-project/Wasabee-IITC#242]
![image](https://user-images.githubusercontent.com/1621399/119021026-38dedb80-b99f-11eb-9c41-d5c381c888c8.png)
Zone selection with combo box is missing.

**Comment by cloudkucooland** [comment]
Let's use the checklist, displaying only a subset of the data for this dialog. This particular dialog is from version 0.5 or so... never really updated.
