### ISSUE TITLE
Markers : Add a "lock" feature

### ISSUE THREAD

**Issue by SebastienForay** [wasabee-project/Wasabee-IITC#252]
This will prevent marker to be deleted when using the "clear all markers" button.
In some case, the marker is so important that it will always be re created by trawl or manually added (example : portal is a HP).

@cloudkucooland backend upgrade will be needed to save it

**Comment by le-jeu** [comment]
Automarked markers have the comment "auto-marked". This is used by the "Clear Automark" button from the blockers dialog to remove all automarked markers.

**Comment by cloudkucooland** [comment]
we can do "lock" as a boolean on markers/links (zones?) does this prevent user editing or just "bulk" processes from editing? If user editing, who can disable the lock? only the lock-er or anyone? Do we need to store the gid of the person who locked it?

**Comment by SebastienForay** [comment]
In fact, this isn't required.
Deleting auto-marked is working perfectly and I didn't noticed how it worked.

Just changing the marker comment prevent it to being auto deleted 👌

**Comment by cloudkucooland** [comment]
my favorite kind of bug-fix! the one that doesn't need to be done!
