### ISSUE TITLE
Drawtools and bookmark import using wrong MPE-Dataset

### ISSUE THREAD

**Issue by MysticJay** [wasabee-project/Wasabee-IITC#260]
**Describe the bug**
With IITC-CE (0.31.0) we have Multi Project Extension (MPE) support with Drawtools and Bookmarks.

Seems to use a hardcoded string to identify the localstorage ID, where it should use the dynamic assigned values in DT and BKMKS

**To Reproduce**
Activate MPE
create set of Bookmarks (in default, three should do)
create a field on that Bookmarks
add a new MPE project in the menu for Bookmarks and Drawtools
create a different set of Bookmarks (far away) and a field with DT.

Now, still on the second project create an OP in wasabee and import the draw.
Portals can not be resolved or will be resolved with the closest of the default projects.

**Expected behavior**
Obvious

**Solution**
Use
`window.plugin.drawTools.KEY_STORAGE`
`window.plugin.bookmarks.KEY_STORAGE`
 not hard coded strings

**Comment by cloudkucooland** [comment]
I've not looked at that code in a while. We will need to ensure that window.plugin.DrawTools exists (if that check isn't already in place). I almost never have DrawTools enabled. 

@TheMitch2 this would be a good enhancement for you to try. If you are willing

**Comment by TheMitch2** [comment]
Doesn't look hard. I'll add this into my projects.

**Comment by MysticJay** [comment]
> Doesn't look hard. I'll add this into my projects.
its pretty well documented. contact me for the links.

**Comment by TheMitch2** [comment]
Fixed with PR#262
