### ISSUE TITLE
Wasabee plugin does not work on IITC

### ISSUE THREAD

**Issue by hectorluisnavas** [wasabee-project/Wasabee-IITC#27]
The Wasabee plugin v.0.13.0 don't works or don't show the panels on IITC CE v0.29.1.20190315.122355.

**Comment by cloudkucooland** [comment]
Can you test the current development build and see if it works?

https://server.wasabee.rocks/static/dev/

**Comment by hectorluisnavas** [comment]
Yes, the plugin has loaded now, so far the available options are the following:
Wasabee Status (doesn't allow login)
OP lists
Quickdraw layers
Multimax Draw
Add links
Add markers
New OP
Clear all OPs
Download OPs (doesn't allow login)
Upload OPs (doesn't allow login)

Portal Link List not available
Swap Anchors not available

**Comment by cloudkucooland** [comment]
Which browser (or IITC mobile)? OS?

If Chrome, does the console show any information when you inspect? Look for things in red.

When you say "doesn't allow login" what exactly happens? Does it prompt and not finish? Or does it not even prompt?

**Comment by hectorluisnavas** [comment]
Chrome 78.0.3904.97, macOS Catalina 10.15.1

The Chrome console show me this when load the intel with plugin active:

`Invalid 'X-Frame-Options' header encountered when loading 'https://server.wasabee.rocks/static/firebase/': 'allow-from https://intel.ingress.com' is not a recognized directive. The header will be ignored.`

When I click on Wasabee Status button show me in console:

`Access to XMLHttpRequest at 'https://accounts.google.com/o/oauth2/auth?client_id=269534461245-jbnes60ebd7u0b8naba19h4vqm7ji219.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fserver.wasabee.rocks%2Fcallback&response_type=code&scope=profile+email&state=capillary-scouting-vkwe' (redirected from 'https://server.wasabee.rocks/me') from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

`Cross-Origin Read Blocking (CORB) blocked cross-origin response https://accounts.google.com/o/oauth2/auth?client_id=269534461245-jbnes60ebd7u0b8naba19h4vqm7ji219.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fserver.wasabee.rocks%2Fcallback&response_type=code&scope=profile+email&state=capillary-scouting-vkwe with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`

When I click in the login button:

`cb=gapi.loaded_0:263 Uncaught (in promise) uO {message: "gapi.auth2.authorize cannot be called after Google…hen given a 'clientId' and a 'scope' parameters).", stack: "gapi.auth2.ExternallyVisibleError: gapi.auth2.auth…t.eval (webpack:///./src/code/wasabee.js?:180:29)"}`

Doesn't allow login --> it doesn't even prompt

**Comment by cloudkucooland** [comment]
Interesting. I'll have to do some research. The CORB issue is very strange indeed. I'm not seeing this on Chrome Version 78.0.3904.97 (Mac OS 10.13 and 10.14 but that shouldn't make a difference in this case).

I am setting the Access-Control-Allow-Origin header, so maybe you've got a proxy server issue? Or a firewall is mucking up the data? Can you try from another location or disabling firewalls/proxies?

**Comment by hectorluisnavas** [comment]
firewall and proxies are turned off

**Comment by cloudkucooland** [comment]
should be all fixed now with 0.14.16
