### ISSUE TITLE
iOS: Problem seeing lower buttons

### ISSUE THREAD

**Issue by misuo** [wasabee-project/Wasabee-IITC#272]
On iOS 14.6, using Wasabee v0.21.01 the non-active lower buttons are barely visible (gray text on green background). 

![image](https://user-images.githubusercontent.com/21021375/123514680-74eb1780-d694-11eb-9153-c35503acdac2.png)

**Comment by le-jeu** [comment]
wrong repo, moved to  wasabee-project/Wasabee-Mobile-Xamarin#37
