### ISSUE TITLE
Advanced settings

### ISSUE THREAD

**Issue by TheMitch2** [wasabee-project/Wasabee-IITC#275]
Change Wasabee settings to advanced settings and move clear data to that location. Also a warning to not touch what you don't understand.

**Comment by VE6SRV** [comment]
Being provided information about what the buttons do is the only way for a user to learn what a button does outside of trying the button to see what it does. New users are told to go try Wasabee and learn what it does. You can't have it both ways.

In the Wasabee Zoom Week 3 video at 33:45, Scott provides explicit instruction to "log out, clear local ops, and the pull it down again" if local changes are made accidentally, and you want to revert back to the version on the server. https://youtu.be/iHK2JRqsQbo?t=2025

There is no mention that when you clear data that a new local op will be created. Once the user is aware that a local op always has to be present in Wasabee-IITC, it's easy to understand. Simple explanation of the function of the software is all that is needed.

**Comment by TheMitch2** [comment]
The warning for not touching what you don't understand would only apply to the Wasabee/advanced settings. Not general features. The general features are fairly self explanatory and such a warning would not be necessary.

Also, following instructions from a video would not qualify. If you're going through troubleshooting and you're told to click a button you'll likely receive an explanation. What I don't want is for someone to go in and clear unnecessarily while not understanding and then complaining things don't work.

**Comment by cloudkucooland** [comment]
Especially given the age of the video... things improve.

**Comment by bgillock** [comment]
Related, the enhancement to store sort columns/direction chosen in some dialogs, used the localStorage. The keys are not in the static constants list, so they will not be cleared when ClearAllData is performed. Suggest also clearing all localStorage where a key includes 'wasabee'.

**Comment by bgillock** [comment]
This is targeted for 0.21 but is still open. Looks like the Clear Data button has moved in dev. The problem is the Wasabee Settings appears in the IITC portal dialog which is shared by other non-Wasabee plugins. Changing the dialog title to Advanced settings and leaving it as Wasabee settings in the IITC toolbox might be a good common ground.

**Comment by le-jeu** [comment]
solved by #332
