### ISSUE TITLE
Adding markers to an Op while logged out causes an error on iOS IITC-Wasabee plugin 

### ISSUE THREAD

**Issue by VE6SRV** [wasabee-project/Wasabee-IITC#278]
On iOS, IITC-CE with Wasabee plugin:

When logged out of an operation, if you click on the "Markers" button on the main toolbar, and then select "+ Marker", as the "Add Markers Dialog" box opens, the Wasabee bee turns green. After adding your markers, if you check on operations, you will find a new Op has been created. I beleive that this shows that you are not logged into the server, and Wasabee is trying to create a new Op as no Ops are available.

If you click on the green bee and tell it to log out, it will throw an error.

SyntaxError: The string did not match the expected pattern.

I am running an iphone 11, software version 14.6, IITC-CE release build v 0.31.1 Wasabee version 0.19.1

If I try the same thing on my desktop version, attempting to add a marker while logged out does not open the "Add Markers Dialog" box.

**Comment by le-jeu** [comment]
> When logged out of an operation, if you click on the "Markers" button on the main toolbar, and then select "+ Marker", as the "Add Markers Dialog" box opens, the Wasabee bee turns green.

Do you mean log out from wasabee ? (you don't log out of an operation)

> If I try the same thing on my desktop version, attempting to add a marker while logged out does not open the "Add Markers Dialog" box.

fxed in 7deb81531fa1cac04d4d6b4ff23af103a07dbfd7 (&today release)

**Comment by VE6SRV** [comment]
Forced an update in IITC to get the latest scripts. 

Running 0.20.20210716095658 and still seeing the same issue. 

Not sure if this is 7deb815 or not.

**Comment by le-jeu** [comment]
which one ? you described 2 bugs

**Comment by VE6SRV** [comment]
Sorry, let me clarify.

I am running an iphone 11, software version 14.6, IITC-CE release build v 0.31.1 Wasabee version  0.20.20210716095658

On iOS, IITC-CE with Wasabee plugin version  0.20.20210716095658:

When logged out of Wasabee, if you click on the "Markers" button on the main toolbar, and then select "+ Marker", as the "Add Markers Dialog" box opens, the Wasabee bee turns green. 

This appears to be a bug as I should still be logged out.

Further to this, as supporting evidence that I beleive I am not logged into Wasabee, I see the following.

After adding your markers, if you check on operations, you will find a new Op has been created. I beleive that this shows that you are not logged into the server, and Wasabee is trying to create a new Op as no Ops are available.

In an attempt to check on the logged in/logged out status:

If you click on the green bee and tell it to log out, it will throw an error.

SyntaxError: The string did not match the expected pattern.

Again, this appears to indicate that Wasabee was not in a logged in state.

I believe the bug I am describing is the fact that as soon as the Add Markers dialog opens, Wasabee changes the to show a logged in state (as observed by the green bee icon). The rest of the description is supporting information that I observe.

**Comment by crystalwizard** [comment]
this was fixed this morning

**Comment by VE6SRV** [comment]
Excellent! Thanks for the quick fix. I'll have to wait until 7deb815 becomes available for download.

Thanks!

**Comment by le-jeu** [comment]
I summarize the steps you did:
 - login into wasabee
 - logout
 - add a marker

the wasabee icon turns green

---

do you confirm *all* steps ?

**Comment by VE6SRV** [comment]
Tested this morning, and the issue no longer occurs. Thank you!
