### ISSUE TITLE
Use Offle cache in autodraw

### ISSUE THREAD

**Issue by Falenone** [wasabee-project/Wasabee-IITC#285]
Ability to have https://github.com/sp00x/iitc-offle cache to be used in autodraw just like normal portals on the map

**Comment by le-jeu** [comment]
unless we add a plugin system into wasabee for optional features, I'm against interacting directly with offle data while offle could expose its data with the iitc `window.portals` layer, like the official [cache plugin](https://iitc.app/download_desktop.html#cache-portals-on-map_bqy_jonatkins_release)

**Comment by cloudkucooland** [comment]
I agree. This does not belong in Wasabee-IITC, but could be part of a 3rd party plugin. At best, we could expose a place to register functions to read from other caches.

**Comment by Falenone** [comment]
This was resolved by LeJeu by making changes Offle itself. Now Offle shows portals as placeholders/neutral portals and they do get included in Wasabee autodraw
