### ISSUE TITLE
Feature to quickly select and delete multiple markers

### ISSUE THREAD

**Issue by misuo** [wasabee-project/Wasabee-IITC#293]
I have this use case where I want to be able to quickly to delete a lot of markers.

It would be very nice to have some sort of multiple selection of markers to delete them all in one go. The most elegant way would be by selecting them using a mouse drag-and-drop rectangle selection tool. Today I have to select, then delete for each and everyone. Quite slow process.

This is a more appropriate feature on desktop than when working on mobile/tablet.

**Comment by cloudkucooland** [comment]
The markers dialog should let you delete individuals without having to find them on the map.

IITC doesn't have an OS-like selection feature. Would "delete all markers in zone X" be OK?

**Comment by le-jeu** [comment]
#305 adds a delete mode (one click per marker), a bit different from rectangle selection
see https://github.com/wasabee-project/Wasabee-IITC/issues/298#issuecomment-1005962973

do we need more ?

**Comment by bgillock** [comment]
#305 works nicely, my vote says it is good enough.
