### ISSUE TITLE
Live location : Users don't know that this isn't available in mobile IITC

### ISSUE THREAD

**Issue by SebastienForay** [wasabee-project/Wasabee-IITC#297]
We need something to tell users to use the Wasabee Mobile App OR Telegram bot for live location sharing.

**Comment by TheMitch2** [comment]
We do this in chat when users ask. Do you have any specific recommendations for how to handle it in app?

**Comment by le-jeu** [comment]
Sending current location from iitc makes sense but IITC mobile cannot guarantee to send live location (it pretty much guarantees it won't unless the app is open).

Currently, the iitc plugin sends a location on rare occasion :
  - the user press the button "Send location" from the iitc toolbox
  - on login if the user enabled "Send location" in (local) settings
  - on iitc resume (when the user switch back to the IITC app) and they enabled the "Send location" in (local) settings

**Comment by SebastienForay** [comment]
Maybe we could go for a new sub menu action, with some warnings availables in a list ?
![image](https://user-images.githubusercontent.com/1621399/148268260-2f54c90b-7956-44d0-a6aa-da527f191671.png)

For example, warnings about push notification for live updates not available in mobile iitc, live location updates not available, ...

**Comment by le-jeu** [comment]
Can a short detail on this option be enough ?

    Share Location (only when IITC is in foreground)

![image](https://user-images.githubusercontent.com/64744459/152612446-97cf6b01-1699-4fc9-942b-dbe8f95116c5.png)

**Comment by le-jeu** [comment]
#344 introduces a live location on IITC-Mobile when in foreground
Option name is `Share Location (only when IITC is in foreground)` in this case.

Another choice can be to not change anything except the option name (for disambiguation) :
`Share Location (only at IITC opening and at Log In)`

Some agents use this feature without expecting live update.
