### ISSUE TITLE
OP editing : Quick edits

### ISSUE THREAD

**Issue by SebastienForay** [wasabee-project/Wasabee-IITC#298]
Request :

Add a "quick delete" mode for Anchors / Links and Markers.
When this mode is enabled, clicking any of those will delete it.

**Comment by le-jeu** [comment]
Could this be a Quick Draw mode or a specific button ?

In any case, I suppose the feature would work as follow:
 - toggling marker/links to be deleted by click 
 - applying of all selected items or canceling the action

**Comment by SebastienForay** [comment]
Could it be a new mode ? Like in the Draw Tools with the trash button ?
Click on it to enable the mode, and then click on each link / marker / anchor you want to delete.
Click again to disable mode

**Comment by cloudkucooland** [comment]
eraser button or sub-action/mode to quickdraw?

**Comment by SebastienForay** [comment]
I'd say eraser button sounds to be better UX than sub action

**Comment by SebastienForay** [comment]
The new button to activate deletion mode : 
![image](https://user-images.githubusercontent.com/1621399/148267705-81534484-7e8e-441a-a52d-e3ff7d409869.png)

When in action : 
![image](https://user-images.githubusercontent.com/1621399/148267742-367c664a-1926-4b8a-8ae2-c7b7daabb05a.png)

Click apply and they're gone : 
![image](https://user-images.githubusercontent.com/1621399/148267791-aa79d1c4-a971-4a32-948b-53315adffd69.png)
