### ISSUE TITLE
Marker : Bulk add same marker type

### ISSUE THREAD

**Issue by SebastienForay** [wasabee-project/Wasabee-IITC#309]
When adding markers, it would be practical to have an option which when enabled allows user to click portals one by one to add the selected marker type.

Suggestion :
In the "Add marker" popup, add a checkbox to enable the mode.
![image](https://user-images.githubusercontent.com/1621399/148262347-d6a37b5e-2940-4e79-ac53-37705ebc7df8.png)

When enabled, the selected marker type is added each time a portal is selected with the associated parameters.

**Comment by cloudkucooland** [comment]
I've been thinking through something along those lines as well. I find myself placing many markers of the same type at once. I have no suggestions, just voicing support for exploring the idea.
