### ISSUE TITLE
Marker: support duplicate marker type on single portal

### ISSUE THREAD

**Issue by le-jeu** [wasabee-project/Wasabee-IITC#319]
This was a limitation in early version of the server that was lifted some versions ago.
This is different from multi-assignments.

**Use cases**
 - Meet up at different deltas at the same portal (or farm/upgrade)
 - Destroy/Capture/Virus/Repeat
 - Multiple Other markers
 - User imagination

**Comment by cloudkucooland** [comment]
No objection. The initial restriction was due to a client-side issue. We made it impossible to add multiples at the server to get-around the client problem. There is no reason to keep this restriction in place now.

**Comment by bgillock** [comment]
This would amount to removing the code that disables the marker types in the select list. I suggest doing this before #309 as it makes the bulk logic simpler.
