### ISSUE TITLE
Feature: Swap marker

### ISSUE THREAD

**Issue by le-jeu** [wasabee-project/Wasabee-IITC#320]
Depending on the support of #319, this may need to handle a swap to a portal with the same marker already.

Current code assumes markers cannot be moved: the marker ID must changed when swapped.

**Comment by bgillock** [comment]
What is the use case for moving markers to new portal? One use case could be "When I swap to a portal in the same state as the original portal (blue, green or neutral), move the markers to the new portal, and keep any existing markers."

**Comment by le-jeu** [comment]
Usual cases: 
 - portal location edit
 - draw import (faked portals)
