### ISSUE TITLE
Dialog: [OK] button is confusing on some dialogs

### ISSUE THREAD

**Issue by le-jeu** [wasabee-project/Wasabee-IITC#323]
Most dialogs have a [OK] button that either confirms a user input, or just closes the dialog.
This can be confusing for the user.

![image](https://user-images.githubusercontent.com/64744459/149655434-d95b14c9-0410-4971-a7f8-8b01d0256ec5.png)

![image](https://user-images.githubusercontent.com/64744459/149655455-1b2b52fc-b000-40a9-937d-f14b7154ea0c.png)

We first need to **identify all confusing dialogs**, taking account that some dialogs with user input  don't wait for [OK] to use/apply the user input.

Solution can be:
 1. Renaming [OK] to [Close] when there is nothing to confirm
 2. Remove the [OK] button, the cross in the title bar already close the dialog
 3. ...

**Comment by cloudkucooland** [comment]
I think removing the [OK] button and leaving the [x] would be lest confusing to most users.

Does the new dialog framework make this easier than it used to be? These jQueryUI dialog buttons are annoying to code.

**Comment by le-jeu** [comment]
## OK == Close
 - Team list
 - New Op
 - WD Keys
 - Checklist
 - Blockers
 - Keys list
 - Export
 - AutoDraw (list)
 - Add marker
 - Marker list
 - Link list
 - Op permissions

## Update on change but OK is nice as UX
 - Assign
 - Set Comment
 - Set state
 - Settings
 - Skins
 - Op settings
 - Zones (confusing here)

is this complete ?

**Comment by le-jeu** [comment]
close by https://github.com/wasabee-project/Wasabee-IITC/commit/fc8663b4efd3445d738c0157ea2cb4267d9a87be
