### ISSUE TITLE
The code on CDN2 contains incorrect website links

### ISSUE THREAD

**Issue by crystalwizard** [wasabee-project/Wasabee-IITC#329]
https://cdn2.wasabee.rocks/  has  an issue with the three server login buttons. Currently the code shows:

<div class="lead serverlist"> 
      <a href="https://am.wasabee.rocks/me" class="btn btn-success btn-block">Login to Americas Server</a> 
      <a href="https://eu.wasabee.rocks/me" class="btn btn-success btn-block">Login to EU Server</a> 
      <a href="https://ap.wasabee.rocks/me" class="btn btn-success btn-block">Login to Asia/Pacific Server</a> 
    </div>

Clicking on them does not redirect to the new rocks website.  Please remove the server login buttons and replace with a single button linked to wasabee-project.github.io/Wasabee-WebUI/

**Comment by le-jeu** [comment]
Wrong repo, but ~fixed
