### ISSUE TITLE
Anchor popup : Show self key count

### ISSUE THREAD

**Issue by SebastienForay** [wasabee-project/Wasabee-IITC#337]
![image](https://user-images.githubusercontent.com/1621399/152382476-d1417cb5-0ded-41a3-bd04-33562315ce09.png)

Right now, we're displaying total keys count over number of keys required. Total keys count is the total of keys registered by every teams members on the OP.
But in some cases, we could need to know how many keys I (really I, as single agent) have in MY inventory.

Request is to add a line with "My keys" or add my keys count to the current displayed info

NB : 
Using the "Inventory plugin" by @le-jeu, I can see how many keys I have, but having it withing Wasabee plugin would be great
![image](https://user-images.githubusercontent.com/1621399/152383048-7f8be056-0090-4aee-987a-36395e6cd7d6.png)

**Comment by le-jeu** [comment]
From a7269999 (here, 0 link assigned to me, but I have 15 keys)
![image](https://user-images.githubusercontent.com/64744459/197358045-3f037d76-9bba-4652-914c-8426633ac8ff.png)

**Comment by SebastienForay** [comment]
Didn't seen it before, but that's perfect! Thank you @le-jeu :)
