### ISSUE TITLE
Slight reformatting of Button Layout

### ISSUE THREAD

**Issue by eagsc7** [wasabee-project/Wasabee-IITC#34]
The Quick Draw Mouseover should be called Fielding Options.  The side menu being Quick Draw (Current functionality), MultiMax, Fanfield, and the other fielding Types. 

Add Links would become a standalone option for now (unless there's other types of links someone could think of....)

**Comment by cloudkucooland** [comment]
the quickdraw "end" button flys out . I'm not sure combining it with the other linking options is possible. I'll have to try to see.

**Comment by eagsc7** [comment]
If Quickdraw was selected from the flyout menu, could the End still pop out in basically the same fashion.

**Comment by cloudkucooland** [comment]
> If Quickdraw was selected from the flyout menu, could the End still pop out in basically the same fashion.

Maybe, thats what I need to test.

**Comment by crystalwizard** [comment]
I need clarification on this. you said:
>The Quick Draw Mouseover should be called Fielding Options. The side menu being Quick Draw (Current functionality), MultiMax, Fanfield, and the other fielding Types.<

The link button has the add link, multimax, fanfield, and so on attached to it. the only thing that quick draw layers does is a set of layers, and that's where the mouse-over tool tip is. Are you wanting the text changed to "Quick Draw Fielding Options" on the mouse-over tool tip for that, or a tool tip for fielding options added to the link button?

**Comment by eagsc7** [comment]
> The link button has the add link, multimax, fanfield, and so on attached to it. the only thing that quick draw layers does is a set of layers, and that's where the mouse-over tool tip is. Are you wanting the text changed to "Quick Draw Fielding Options" on the mouse-over tool tip for that, or a tool tip for fielding options added to the link button?

The Quick Draw Layers would become
Quick draw // Multimax // Fanfield // (Other Field Types)

The Add Links would become
Add Links // Starburst

Starburst would stay with links now, cause your only creating links.

**Comment by cloudkucooland** [comment]
I'm not changing how QD works. It will remain its own button.
