### ISSUE TITLE
Can't store keys on hand value for a Get Keys type of Marker on a portal not in the operation

### ISSUE THREAD

**Issue by bgillock** [wasabee-project/Wasabee-IITC#340]
When a My Count is entered for a portal which only has a Get Keys Marker on it, an error is thrown by the server and keys on hand is not updated. 

![image](https://user-images.githubusercontent.com/17684691/152693061-2c34a958-0524-4630-af62-5a5c0781dd67.png)

To duplicate:

1. Select a portal not in the operation already
2. Select + Markers
3. Set the Type of the marker to Get Keys
4. Select Add
5. Bring up the Keys dialog
6. Enter a number in the My Count for the portal selected in 1.

Expect the server to get updated to reflect the count. Instead get a 406 from the server indicating the portal is not in the operation. Key list shows a new On Hand count.

**Comment by le-jeu** [comment]
Fix by 4b63417646b3403a81026725b44786d8385b66aa
