### ISSUE TITLE
Homogeneous Fielding ops

### ISSUE THREAD

**Issue by eagsc7** [wasabee-project/Wasabee-IITC#35]
In Fielding, new option of Homogeneous Field.

Homogeneous Fielding Ops.  
- Anchor1 
- Anchor 2
- Anchor 3

considers ONLY the portals INSIDE

*Mechanics: 
Counts all portals
splits them into 3 equal groups
Draws 2nd layer to those groups
Splits each group in 3, and draws a layer inside each area.  

Continues to a MAX of 6 Layers, OR until there is a inner field that does NOT have a portal inside it.  If not 6, then it message pops up " Only 5 Homogeneous layers available here."
As Reference:
https://www.youtube.com/watch?v=0xoQsG3-vLA on Homogeneous fielding Ops.

**Comment by cloudkucooland** [comment]
TBD: clear debug info on clear links

**Comment by cloudkucooland** [comment]
> TBD: clear debug info on clear links

done in most recent change
