### ISSUE TITLE
Flip Flop Fan Fields

### ISSUE THREAD

**Issue by eagsc7** [wasabee-project/Wasabee-IITC#36]
In Fielding:
Flip Flop Fan Fields.  

- Max Links - 8,24,40 (Dropdown for the values)  If 24, then "Requires 2 SBUL".  If 40, then "Requires 2 agents and 2 SBUL each" 
- Anchor1 - Where everything throws FROM
- Anchor2 - Base Link to Anchor3
- Anchor3 - Base Link from Anchor2

*Mechanics:
1) ONLY Portals inside all three anchors are checked.  
2) Base link from Anchor2 to Anchor3.  <<LIST: Flip_List>> Adds each portal to the list for the Anchor1 Throw order
3) Closest portal to the Base link on the Anchor1 Side,   throws to Anchor2 and 3. <<LIST: Flip_List>>
4) On each of the just created links, the closest portal is selected and thrown to the Previous and second previous(or outside) Link.
5) Repeat 3 and 4 until Either 24 or 40 Total portals are worked through.  
6) Goto Anchor1, and throw Outbound To the portals in the order as shown on the <<LIST: Flip_List>>.

**Comment by le-jeu** [comment]
closed by #288
