### ISSUE TITLE
Cobweb Fields

### ISSUE THREAD

**Issue by eagsc7** [wasabee-project/Wasabee-IITC#38]
Fielding >> Cobweb
https://www.youtube.com/watch?v=yvvrHEtkxGc

- Anchor1 outside
- Anchor2 outside
- Anchor3 outside

 Looks at and figures for all portals Inside them.  

Possibly with being able to go to each anchor area(save the portal GUID and location) and figure for larger areas in that fashion.

**Comment by eagsc7** [comment]
Would be the functionality of "Spirograph", but automated as above...

https://iitc.aradiv.de/?page=3

**Comment by cloudkucooland** [comment]
I've got an algorithm in mind that should be pretty fast. I'm not jacking ENL secure code.

**Comment by cloudkucooland** [comment]
Does my onion/rose algo meet this need?

**Comment by cloudkucooland** [comment]
calling this one done.
