### ISSUE TITLE
Cross Draw detection...

### ISSUE THREAD

**Issue by eagsc7** [wasabee-project/Wasabee-IITC#40]
Can there be an alert(popup or else) to alert the user when drawing layers( Non Max or Fan fields) when one drawn layer would "block" another drawn layer.  Similar to Cross-link detection, but instead for Live links, be for the Drawn links.

This could even be in the "Blockers Dialog" but would be exempt of the automark box.

**Comment by cloudkucooland** [comment]
Duplicate with #11
