### ISSUE TITLE
Key List Formatting

### ISSUE THREAD

**Issue by eagsc7** [wasabee-project/Wasabee-IITC#41]
It would be nice to see variation in the Key List box if you are Short, correct, or Long in the keys on hand (Assuming they're already put in)  

i.e  If I have 5 keys and Need 6 for a draw, the background of On Hand could go pale yellow.  If there's 0 on hand, it goes Red to indicate None available(right now).  If I change around the draw(swap links , etc... )and the above mentioned needing 6 ends up dropping to 5 or below, the background (or entire row) could go Green to easially show Keys are available.  

Course when Assigning, a New Column could be added to indicate they're "In the right place" or with the thrower.

**Comment by cloudkucooland** [comment]
![Screen Shot 2020-03-27 at 12 34 44 PM](https://user-images.githubusercontent.com/8037678/77783914-a99e9800-7027-11ea-90b1-ce89f51c1239.png)

done
