### ISSUE TITLE
Add Marker Dialog: Translation texts

### ISSUE THREAD

**Issue by D0BERMAXX** [wasabee-project/Wasabee-IITC#47]
![image](https://user-images.githubusercontent.com/62525049/77588395-b8e8ed00-6f24-11ea-89e7-e9f9972dc03c.png)
Destroy and Marker should have translated text
Add Marker button should have translated text

**Comment by cloudkucooland** [comment]
menu options won't be able to be done in the near term, but the button should

**Comment by crystalwizard** [comment]
button dialog translations finished.

**Comment by D0BERMAXX** [comment]
Checked, validated.

Closing issue!
