### ISSUE TITLE
Ops Dialog: Translation Text

### ISSUE THREAD

**Issue by D0BERMAXX** [wasabee-project/Wasabee-IITC#48]
![image](https://user-images.githubusercontent.com/62525049/77588594-209f3800-6f25-11ea-83a9-e12c4e8b6346.png)
"Operation Name: " should have translation
"Operation Color: " should have translation
I'm contemplating if colors should have translated text as well
"Clear blah blah" button should have translation
"Duplicate Operation" button should have translation

**Comment by cloudkucooland** [comment]
done
