### ISSUE TITLE
Export Dialog: Translations

### ISSUE THREAD

**Issue by D0BERMAXX** [wasabee-project/Wasabee-IITC#49]
![image](https://user-images.githubusercontent.com/62525049/77588786-8390cf00-6f25-11ea-984e-a3dc9f543cb5.png)
"Select all and ..." should have translation

**Comment by cloudkucooland** [comment]
I'd rather that whole bit just went away, it causes problems on touch-enabled devices (phones, iPads, etc)

**Comment by cloudkucooland** [comment]
done
