### ISSUE TITLE
Import Wasabee Draw Dialog: Texts

### ISSUE THREAD

**Issue by D0BERMAXX** [wasabee-project/Wasabee-IITC#51]
![image](https://user-images.githubusercontent.com/62525049/77589046-f601af00-6f25-11ea-9b86-9d7e19efab56.png)
"Get Existing blah..." - suggested "Get drawn DrawTools" or "Get current DrawTools Drawing"

**Comment by crystalwizard** [comment]
changed Get Existing to Import

**Comment by eagsc7** [comment]
My only thought is instead of Get use Paste, but that would make the button longer.  

What about being able to paste in a .rocks Draw link and it pulling the data direct from .rocks.

**Comment by cloudkucooland** [comment]
But it's not pasting, it's getting it from memory. That button saves the whole export/copy/paste/import step, just click it and it does all that for you.

**Comment by cloudkucooland** [comment]
done-enough, when the buttons get translated we can improve on it.
