### ISSUE TITLE
Bulk assign Outbound links....

### ISSUE THREAD

**Issue by eagsc7** [wasabee-project/Wasabee-IITC#53]
When assigning outbound links via the Portal Marker on draws, its assigning that marker to All links.. be it Inbound or Outbound.

**Comment by eagsc7** [comment]
Now, Assign Outbound Links is completely dead.  Checked on Desktop and is not assigning any links.  

Manual assignment of individual links does work still.

**Comment by eagsc7** [comment]
Just tested and it came up to "not logged in" as the Assigned to.  Though -I am logged in-

**Comment by cloudkucooland** [comment]
I've not changed anything in several days, maybe you got a build before I was finished or tested incorrectly?

**Comment by cloudkucooland** [comment]
I'm calling this one done.
