### ISSUE TITLE
mobile friendly UI (small dialogs, short buttons)

### ISSUE THREAD

**Issue by cloudkucooland** [wasabee-project/Wasabee-IITC#80]
which ones?

**Comment by cloudkucooland** [comment]
portal names should be shorter than 12 characters in most dialogs now on mobile devices.

**Comment by cloudkucooland** [comment]
all dialogs moved to grid layout
some columns are hidden on larger dialogs when displayed on small screens
portal names are short on small screens (single and in link)
button sub-action names are shorter on smaller screens
overflow menus have been removed

**Comment by crystalwizard** [comment]
created short english names for buttons.

**Comment by cloudkucooland** [comment]
short portal names in many more places done

complete audit of WasabePortal.displayFormat() done.

**Comment by cmmdr3** [comment]
![0EB0A170-61FA-4AFC-AA24-81B8554E4526](https://user-images.githubusercontent.com/63676232/79271967-ffd15f00-7ea0-11ea-98fd-a0cf0b430cff.jpeg)

On iPhone 11Pro the settings Button is out of Screen after login.

**Comment by cloudkucooland** [comment]
> ![0EB0A170-61FA-4AFC-AA24-81B8554E4526](https://user-images.githubusercontent.com/63676232/79271967-ffd15f00-7ea0-11ea-98fd-a0cf0b430cff.jpeg)
> 
> On iPhone 11Pro the settings Button is out of Screen after login.
> 
> // @Version 0.16.1-2020-04-14T17:57:00.200Z

I think just trimming 2px of padding from either side on @media smaller than 400px  would be enough here.

**Comment by crystalwizard** [comment]
Fixed for Paul's device and other small screen sizes. Calling this done.
