### ISSUE TITLE
draw tools style drawing

### ISSUE THREAD

**Issue by cloudkucooland** [wasabee-project/Wasabee-IITC#83]
click one portal, click next portal, click next portal... don't auto-draw layers or anything, just links.

**Comment by eagsc7** [comment]
Sounds good... would be the base for Add Link.

**Comment by cloudkucooland** [comment]
> Sounds good... would be the base for Add Link.

I really don't like the button layout you've suggested. I have no intention of changing where qd is located or making this the base method.

**Comment by cloudkucooland** [comment]
While working on the mouse-following guides, I learned about some leaflet bugs that will make this difficult. Disabling the followers and putting this on hold for now.

https://github.com/Leaflet/Leaflet/issues/4135
https://github.com/Leaflet/Leaflet/issues/7049
https://github.com/Leaflet/Leaflet/issues/4135

**Comment by cloudkucooland** [comment]
Found a reasonable work-around.

keyboard shortcut - g or / to enable guides
keyboard shortcut - m or t to _t_oggle _m_ode between fields or single links.

guides will interfere with clicking on portals, toggle them on to plan, off to click -- maybe I should use the shift key and just show the guides while it is held down... *ponders*

this is as far as I'm taking this for 0.17.
