### ISSUE TITLE
Audit event propagation 

### ISSUE THREAD

**Issue by cloudkucooland** [wasabee-project/Wasabee-IITC#98]
Liberally sprinkle 

.on(a, "click", L.DomEvent.preventDefault)
.on(a, "click", L.DomEvent.stopPropagation)

to L.DomEvent. calls.

**Comment by cloudkucooland** [comment]
on(a, "click, (ev) => {
....
L.DomEvent.stop(ev);
)};

is better

**Comment by cloudkucooland** [comment]
Test to make sure things still respond... buttons still work, etc.

**Comment by eagsc7** [comment]
just the button issue with End is still there.  

End Clears on 30.1, but does NOT clear on .26.0.30170108.

**Comment by cloudkucooland** [comment]
> just the button issue with End is still there.
> 
> End Clears on 30.1, but does NOT clear on .26.0.30170108.

Unrelated
